// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}



/// How a source should be treated by the native loader.
enum FeedMediaKindMessage: Int {
  case auto = 0
  case progressive = 1
  case hls = 2
}

/// Native playback status for a single controller.
enum PlaybackStatusMessage: Int {
  case idle = 0
  case preparing = 1
  case ready = 2
  case playing = 3
  case paused = 4
  case buffering = 5
  case completed = 6
  case error = 7
  case released = 8
}

/// Why a controller stopped existing.
enum ReleaseReasonMessage: Int {
  case disposed = 0
  case evicted = 1
  case error = 2
  case engineDetached = 3
}

/// How native video output reaches the Flutter scene.
enum RenderModeMessage: Int {
  /// A native view composited by Flutter's platform-view layer.
  case platformView = 0
  /// Frames copied into a Flutter texture, drawn by the Flutter renderer.
  case texture = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeedSourceMessage: Hashable {
  /// Caller-owned stable identifier. Survives pagination and reordering.
  var id: String
  var uri: String
  /// Position in the feed, used only to rank preload priority.
  var rank: Int64
  var kind: FeedMediaKindMessage
  var headers: [String: String]
  /// Optional stable cache identity. When set, it replaces the URI in the
  /// cache key so signed or expiring URLs still share one cache entry.
  var cacheKey: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeedSourceMessage? {
    let id = pigeonVar_list[0] as! String
    let uri = pigeonVar_list[1] as! String
    let rank = pigeonVar_list[2] as! Int64
    let kind = pigeonVar_list[3] as! FeedMediaKindMessage
    let headers = pigeonVar_list[4] as! [String: String]
    let cacheKey: String? = nilOrValue(pigeonVar_list[5])

    return FeedSourceMessage(
      id: id,
      uri: uri,
      rank: rank,
      kind: kind,
      headers: headers,
      cacheKey: cacheKey
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      uri,
      rank,
      kind,
      headers,
      cacheKey,
    ]
  }
  static func == (lhs: FeedSourceMessage, rhs: FeedSourceMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CachePolicyMessage: Hashable {
  var enabled: Bool
  var maxBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CachePolicyMessage? {
    let enabled = pigeonVar_list[0] as! Bool
    let maxBytes = pigeonVar_list[1] as! Int64

    return CachePolicyMessage(
      enabled: enabled,
      maxBytes: maxBytes
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      maxBytes,
    ]
  }
  static func == (lhs: CachePolicyMessage, rhs: CachePolicyMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioPolicyMessage: Hashable {
  var muted: Bool
  var volume: Double
  /// Whether audible playback requests platform audio focus.
  var handleAudioFocus: Bool
  /// iOS only. When false the plugin never reconfigures AVAudioSession; the
  /// host app owns category, mode, and activation.
  var manageAudioSession: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioPolicyMessage? {
    let muted = pigeonVar_list[0] as! Bool
    let volume = pigeonVar_list[1] as! Double
    let handleAudioFocus = pigeonVar_list[2] as! Bool
    let manageAudioSession = pigeonVar_list[3] as! Bool

    return AudioPolicyMessage(
      muted: muted,
      volume: volume,
      handleAudioFocus: handleAudioFocus,
      manageAudioSession: manageAudioSession
    )
  }
  func toList() -> [Any?] {
    return [
      muted,
      volume,
      handleAudioFocus,
      manageAudioSession,
    ]
  }
  static func == (lhs: AudioPolicyMessage, rhs: AudioPolicyMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeedPlayerConfigMessage: Hashable {
  var maxActivePlayers: Int64
  var preloadAhead: Int64
  var preloadBehind: Int64
  var maxConcurrentPreloads: Int64
  var positionUpdateIntervalMs: Int64
  var renderMode: RenderModeMessage
  var cache: CachePolicyMessage
  var audio: AudioPolicyMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeedPlayerConfigMessage? {
    let maxActivePlayers = pigeonVar_list[0] as! Int64
    let preloadAhead = pigeonVar_list[1] as! Int64
    let preloadBehind = pigeonVar_list[2] as! Int64
    let maxConcurrentPreloads = pigeonVar_list[3] as! Int64
    let positionUpdateIntervalMs = pigeonVar_list[4] as! Int64
    let renderMode = pigeonVar_list[5] as! RenderModeMessage
    let cache = pigeonVar_list[6] as! CachePolicyMessage
    let audio = pigeonVar_list[7] as! AudioPolicyMessage

    return FeedPlayerConfigMessage(
      maxActivePlayers: maxActivePlayers,
      preloadAhead: preloadAhead,
      preloadBehind: preloadBehind,
      maxConcurrentPreloads: maxConcurrentPreloads,
      positionUpdateIntervalMs: positionUpdateIntervalMs,
      renderMode: renderMode,
      cache: cache,
      audio: audio
    )
  }
  func toList() -> [Any?] {
    return [
      maxActivePlayers,
      preloadAhead,
      preloadBehind,
      maxConcurrentPreloads,
      positionUpdateIntervalMs,
      renderMode,
      cache,
      audio,
    ]
  }
  static func == (lhs: FeedPlayerConfigMessage, rhs: FeedPlayerConfigMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CreateControllerRequest: Hashable {
  var sourceId: String
  var autoPlay: Bool
  var looping: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateControllerRequest? {
    let sourceId = pigeonVar_list[0] as! String
    let autoPlay = pigeonVar_list[1] as! Bool
    let looping = pigeonVar_list[2] as! Bool

    return CreateControllerRequest(
      sourceId: sourceId,
      autoPlay: autoPlay,
      looping: looping
    )
  }
  func toList() -> [Any?] {
    return [
      sourceId,
      autoPlay,
      looping,
    ]
  }
  static func == (lhs: CreateControllerRequest, rhs: CreateControllerRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ControllerRequest: Hashable {
  var controllerId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ControllerRequest? {
    let controllerId = pigeonVar_list[0] as! Int64

    return ControllerRequest(
      controllerId: controllerId
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId
    ]
  }
  static func == (lhs: ControllerRequest, rhs: ControllerRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SeekRequest: Hashable {
  var controllerId: Int64
  var positionMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SeekRequest? {
    let controllerId = pigeonVar_list[0] as! Int64
    let positionMs = pigeonVar_list[1] as! Int64

    return SeekRequest(
      controllerId: controllerId,
      positionMs: positionMs
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      positionMs,
    ]
  }
  static func == (lhs: SeekRequest, rhs: SeekRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VisibleSourceRequest: Hashable {
  var sourceId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisibleSourceRequest? {
    let sourceId = pigeonVar_list[0] as! String

    return VisibleSourceRequest(
      sourceId: sourceId
    )
  }
  func toList() -> [Any?] {
    return [
      sourceId
    ]
  }
  static func == (lhs: VisibleSourceRequest, rhs: VisibleSourceRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ControllerDoubleRequest: Hashable {
  var controllerId: Int64
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ControllerDoubleRequest? {
    let controllerId = pigeonVar_list[0] as! Int64
    let value = pigeonVar_list[1] as! Double

    return ControllerDoubleRequest(
      controllerId: controllerId,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      value,
    ]
  }
  static func == (lhs: ControllerDoubleRequest, rhs: ControllerDoubleRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ControllerFlagRequest: Hashable {
  var controllerId: Int64
  var value: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ControllerFlagRequest? {
    let controllerId = pigeonVar_list[0] as! Int64
    let value = pigeonVar_list[1] as! Bool

    return ControllerFlagRequest(
      controllerId: controllerId,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      value,
    ]
  }
  static func == (lhs: ControllerFlagRequest, rhs: ControllerFlagRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttachViewRequest: Hashable {
  var controllerId: Int64
  var viewId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttachViewRequest? {
    let controllerId = pigeonVar_list[0] as! Int64
    let viewId = pigeonVar_list[1] as! Int64

    return AttachViewRequest(
      controllerId: controllerId,
      viewId: viewId
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      viewId,
    ]
  }
  static func == (lhs: AttachViewRequest, rhs: AttachViewRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SourceIdsRequest: Hashable {
  var sourceIds: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SourceIdsRequest? {
    let sourceIds = pigeonVar_list[0] as! [String]

    return SourceIdsRequest(
      sourceIds: sourceIds
    )
  }
  func toList() -> [Any?] {
    return [
      sourceIds
    ]
  }
  static func == (lhs: SourceIdsRequest, rhs: SourceIdsRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CacheStatusMessage: Hashable {
  var sourceId: String
  var cachedBytes: Int64
  var totalBytes: Int64
  var isComplete: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CacheStatusMessage? {
    let sourceId = pigeonVar_list[0] as! String
    let cachedBytes = pigeonVar_list[1] as! Int64
    let totalBytes = pigeonVar_list[2] as! Int64
    let isComplete = pigeonVar_list[3] as! Bool

    return CacheStatusMessage(
      sourceId: sourceId,
      cachedBytes: cachedBytes,
      totalBytes: totalBytes,
      isComplete: isComplete
    )
  }
  func toList() -> [Any?] {
    return [
      sourceId,
      cachedBytes,
      totalBytes,
      isComplete,
    ]
  }
  static func == (lhs: CacheStatusMessage, rhs: CacheStatusMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaybackErrorMessage: Hashable {
  var code: String
  var message: String
  var isRecoverable: Bool
  var platformCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaybackErrorMessage? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let isRecoverable = pigeonVar_list[2] as! Bool
    let platformCode: String? = nilOrValue(pigeonVar_list[3])

    return PlaybackErrorMessage(
      code: code,
      message: message,
      isRecoverable: isRecoverable,
      platformCode: platformCode
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      isRecoverable,
      platformCode,
    ]
  }
  static func == (lhs: PlaybackErrorMessage, rhs: PlaybackErrorMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaybackStateEvent: Hashable {
  var controllerId: Int64
  var status: PlaybackStatusMessage
  var error: PlaybackErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaybackStateEvent? {
    let controllerId = pigeonVar_list[0] as! Int64
    let status = pigeonVar_list[1] as! PlaybackStatusMessage
    let error: PlaybackErrorMessage? = nilOrValue(pigeonVar_list[2])

    return PlaybackStateEvent(
      controllerId: controllerId,
      status: status,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      status,
      error,
    ]
  }
  static func == (lhs: PlaybackStateEvent, rhs: PlaybackStateEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PositionEvent: Hashable {
  var controllerId: Int64
  var positionMs: Int64
  var bufferedPositionMs: Int64? = nil
  var durationMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PositionEvent? {
    let controllerId = pigeonVar_list[0] as! Int64
    let positionMs = pigeonVar_list[1] as! Int64
    let bufferedPositionMs: Int64? = nilOrValue(pigeonVar_list[2])
    let durationMs: Int64? = nilOrValue(pigeonVar_list[3])

    return PositionEvent(
      controllerId: controllerId,
      positionMs: positionMs,
      bufferedPositionMs: bufferedPositionMs,
      durationMs: durationMs
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      positionMs,
      bufferedPositionMs,
      durationMs,
    ]
  }
  static func == (lhs: PositionEvent, rhs: PositionEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MetricsEvent: Hashable {
  var controllerId: Int64
  var rebufferCount: Int64
  /// Monotonic total for the controller's lifetime on both platforms.
  var droppedFrames: Int64
  var timestampMs: Int64
  /// Milliseconds from controller creation to the first rendered video frame.
  var firstFrameLatencyMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MetricsEvent? {
    let controllerId = pigeonVar_list[0] as! Int64
    let rebufferCount = pigeonVar_list[1] as! Int64
    let droppedFrames = pigeonVar_list[2] as! Int64
    let timestampMs = pigeonVar_list[3] as! Int64
    let firstFrameLatencyMs: Int64? = nilOrValue(pigeonVar_list[4])

    return MetricsEvent(
      controllerId: controllerId,
      rebufferCount: rebufferCount,
      droppedFrames: droppedFrames,
      timestampMs: timestampMs,
      firstFrameLatencyMs: firstFrameLatencyMs
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      rebufferCount,
      droppedFrames,
      timestampMs,
      firstFrameLatencyMs,
    ]
  }
  static func == (lhs: MetricsEvent, rhs: MetricsEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoSizeEvent: Hashable {
  var controllerId: Int64
  /// Decoded pixel dimensions, before [rotationDegrees] is applied.
  var width: Int64
  var height: Int64
  /// Clockwise rotation the renderer must apply, in degrees.
  var rotationDegrees: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoSizeEvent? {
    let controllerId = pigeonVar_list[0] as! Int64
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let rotationDegrees = pigeonVar_list[3] as! Int64

    return VideoSizeEvent(
      controllerId: controllerId,
      width: width,
      height: height,
      rotationDegrees: rotationDegrees
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      width,
      height,
      rotationDegrees,
    ]
  }
  static func == (lhs: VideoSizeEvent, rhs: VideoSizeEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ControllerLifecycleEvent: Hashable {
  var controllerId: Int64
  var reason: ReleaseReasonMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ControllerLifecycleEvent? {
    let controllerId = pigeonVar_list[0] as! Int64
    let reason = pigeonVar_list[1] as! ReleaseReasonMessage

    return ControllerLifecycleEvent(
      controllerId: controllerId,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      reason,
    ]
  }
  static func == (lhs: ControllerLifecycleEvent, rhs: ControllerLifecycleEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FeedMediaKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlaybackStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ReleaseReasonMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RenderModeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return FeedSourceMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return CachePolicyMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return AudioPolicyMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return FeedPlayerConfigMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return CreateControllerRequest.fromList(self.readValue() as! [Any?])
    case 138:
      return ControllerRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return SeekRequest.fromList(self.readValue() as! [Any?])
    case 140:
      return VisibleSourceRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return ControllerDoubleRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return ControllerFlagRequest.fromList(self.readValue() as! [Any?])
    case 143:
      return AttachViewRequest.fromList(self.readValue() as! [Any?])
    case 144:
      return SourceIdsRequest.fromList(self.readValue() as! [Any?])
    case 145:
      return CacheStatusMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return PlaybackErrorMessage.fromList(self.readValue() as! [Any?])
    case 147:
      return PlaybackStateEvent.fromList(self.readValue() as! [Any?])
    case 148:
      return PositionEvent.fromList(self.readValue() as! [Any?])
    case 149:
      return MetricsEvent.fromList(self.readValue() as! [Any?])
    case 150:
      return VideoSizeEvent.fromList(self.readValue() as! [Any?])
    case 151:
      return ControllerLifecycleEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FeedMediaKindMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlaybackStatusMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReleaseReasonMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? RenderModeMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? FeedSourceMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CachePolicyMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? AudioPolicyMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? FeedPlayerConfigMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? CreateControllerRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ControllerRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? SeekRequest {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? VisibleSourceRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? ControllerDoubleRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ControllerFlagRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? AttachViewRequest {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? SourceIdsRequest {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? CacheStatusMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? PlaybackErrorMessage {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? PlaybackStateEvent {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? PositionEvent {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? MetricsEvent {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? VideoSizeEvent {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? ControllerLifecycleEvent {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeFeedPlayerHostApi {
  func initialize(config: FeedPlayerConfigMessage) throws
  /// Replaces the whole feed.
  func setSources(sources: [FeedSourceMessage]) throws
  /// Appends a page without renumbering existing sources.
  func appendSources(sources: [FeedSourceMessage]) throws
  func removeSources(request: SourceIdsRequest) throws
  func createController(request: CreateControllerRequest) throws -> Int64
  func disposeController(request: ControllerRequest) throws
  func play(request: ControllerRequest) throws
  func pause(request: ControllerRequest) throws
  func seekTo(request: SeekRequest) throws
  func setVolume(request: ControllerDoubleRequest) throws
  func setMuted(request: ControllerFlagRequest) throws
  func setPlaybackSpeed(request: ControllerDoubleRequest) throws
  func setLooping(request: ControllerFlagRequest) throws
  /// Applies to every controller, current and future.
  func setAudioPolicy(policy: AudioPolicyMessage) throws
  func setVisibleSource(request: VisibleSourceRequest) throws
  /// Drops persisted media bytes for the given sources, or all of them when
  /// the list is empty.
  func evictCachedMedia(request: SourceIdsRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func clearMediaCache(completion: @escaping (Result<Void, Error>) -> Void)
  func cacheStatus(request: VisibleSourceRequest, completion: @escaping (Result<CacheStatusMessage, Error>) -> Void)
  func cacheUsageBytes(completion: @escaping (Result<Int64, Error>) -> Void)
  func attachView(request: AttachViewRequest) throws
  func detachView(request: ControllerRequest) throws
  /// Binds the controller to a Flutter texture and returns its id.
  func attachTexture(request: ControllerRequest) throws -> Int64
  func detachTexture(request: ControllerRequest) throws
  func disposeAll() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeFeedPlayerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `NativeFeedPlayerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeFeedPlayerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! FeedPlayerConfigMessage
        do {
          try api.initialize(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Replaces the whole feed.
    let setSourcesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setSources\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSourcesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourcesArg = args[0] as! [FeedSourceMessage]
        do {
          try api.setSources(sources: sourcesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSourcesChannel.setMessageHandler(nil)
    }
    /// Appends a page without renumbering existing sources.
    let appendSourcesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.appendSources\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      appendSourcesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourcesArg = args[0] as! [FeedSourceMessage]
        do {
          try api.appendSources(sources: sourcesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      appendSourcesChannel.setMessageHandler(nil)
    }
    let removeSourcesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.removeSources\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeSourcesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SourceIdsRequest
        do {
          try api.removeSources(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeSourcesChannel.setMessageHandler(nil)
    }
    let createControllerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.createController\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createControllerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CreateControllerRequest
        do {
          let result = try api.createController(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createControllerChannel.setMessageHandler(nil)
    }
    let disposeControllerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.disposeController\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeControllerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.disposeController(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeControllerChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.play(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.pause(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SeekRequest
        do {
          try api.seekTo(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerDoubleRequest
        do {
          try api.setVolume(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    let setMutedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setMuted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMutedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerFlagRequest
        do {
          try api.setMuted(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMutedChannel.setMessageHandler(nil)
    }
    let setPlaybackSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setPlaybackSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPlaybackSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerDoubleRequest
        do {
          try api.setPlaybackSpeed(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPlaybackSpeedChannel.setMessageHandler(nil)
    }
    let setLoopingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setLooping\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLoopingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerFlagRequest
        do {
          try api.setLooping(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLoopingChannel.setMessageHandler(nil)
    }
    /// Applies to every controller, current and future.
    let setAudioPolicyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setAudioPolicy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAudioPolicyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let policyArg = args[0] as! AudioPolicyMessage
        do {
          try api.setAudioPolicy(policy: policyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAudioPolicyChannel.setMessageHandler(nil)
    }
    let setVisibleSourceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setVisibleSource\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVisibleSourceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VisibleSourceRequest
        do {
          try api.setVisibleSource(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVisibleSourceChannel.setMessageHandler(nil)
    }
    /// Drops persisted media bytes for the given sources, or all of them when
    /// the list is empty.
    let evictCachedMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.evictCachedMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      evictCachedMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SourceIdsRequest
        api.evictCachedMedia(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      evictCachedMediaChannel.setMessageHandler(nil)
    }
    let clearMediaCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.clearMediaCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearMediaCacheChannel.setMessageHandler { _, reply in
        api.clearMediaCache { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearMediaCacheChannel.setMessageHandler(nil)
    }
    let cacheStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.cacheStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cacheStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VisibleSourceRequest
        api.cacheStatus(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cacheStatusChannel.setMessageHandler(nil)
    }
    let cacheUsageBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.cacheUsageBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cacheUsageBytesChannel.setMessageHandler { _, reply in
        api.cacheUsageBytes { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cacheUsageBytesChannel.setMessageHandler(nil)
    }
    let attachViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.attachView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      attachViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AttachViewRequest
        do {
          try api.attachView(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      attachViewChannel.setMessageHandler(nil)
    }
    let detachViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.detachView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detachViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.detachView(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      detachViewChannel.setMessageHandler(nil)
    }
    /// Binds the controller to a Flutter texture and returns its id.
    let attachTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.attachTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      attachTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          let result = try api.attachTexture(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      attachTextureChannel.setMessageHandler(nil)
    }
    let detachTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.detachTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detachTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.detachTexture(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      detachTextureChannel.setMessageHandler(nil)
    }
    let disposeAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.disposeAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeAllChannel.setMessageHandler { _, reply in
        do {
          try api.disposeAll()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeAllChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class PlaybackStateEventsStreamHandler: PigeonEventChannelWrapper<PlaybackStateEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: PlaybackStateEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.playbackStateEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PlaybackStateEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}

class PositionEventsStreamHandler: PigeonEventChannelWrapper<PositionEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: PositionEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.positionEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PositionEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}

class MetricsEventsStreamHandler: PigeonEventChannelWrapper<MetricsEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: MetricsEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.metricsEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<MetricsEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}

class VideoSizeEventsStreamHandler: PigeonEventChannelWrapper<VideoSizeEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: VideoSizeEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.videoSizeEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<VideoSizeEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}

class LifecycleEventsStreamHandler: PigeonEventChannelWrapper<ControllerLifecycleEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: LifecycleEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.lifecycleEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<ControllerLifecycleEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
