// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct InitializeRequest: Hashable {
  var maxCachedPlayers: Int64
  var preloadCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitializeRequest? {
    let maxCachedPlayers = pigeonVar_list[0] as! Int64
    let preloadCount = pigeonVar_list[1] as! Int64

    return InitializeRequest(
      maxCachedPlayers: maxCachedPlayers,
      preloadCount: preloadCount
    )
  }
  func toList() -> [Any?] {
    return [
      maxCachedPlayers,
      preloadCount,
    ]
  }
  static func == (lhs: InitializeRequest, rhs: InitializeRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoSourceMessage: Hashable {
  var url: String
  var index: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoSourceMessage? {
    let url = pigeonVar_list[0] as! String
    let index = pigeonVar_list[1] as! Int64

    return VideoSourceMessage(
      url: url,
      index: index
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      index,
    ]
  }
  static func == (lhs: VideoSourceMessage, rhs: VideoSourceMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreloadRequest: Hashable {
  var sources: [VideoSourceMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreloadRequest? {
    let sources = pigeonVar_list[0] as! [VideoSourceMessage]

    return PreloadRequest(
      sources: sources
    )
  }
  func toList() -> [Any?] {
    return [
      sources
    ]
  }
  static func == (lhs: PreloadRequest, rhs: PreloadRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CreateControllerRequest: Hashable {
  var url: String
  var index: Int64
  var autoPlay: Bool
  var looping: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateControllerRequest? {
    let url = pigeonVar_list[0] as! String
    let index = pigeonVar_list[1] as! Int64
    let autoPlay = pigeonVar_list[2] as! Bool
    let looping = pigeonVar_list[3] as! Bool

    return CreateControllerRequest(
      url: url,
      index: index,
      autoPlay: autoPlay,
      looping: looping
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      index,
      autoPlay,
      looping,
    ]
  }
  static func == (lhs: CreateControllerRequest, rhs: CreateControllerRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ControllerRequest: Hashable {
  var controllerId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ControllerRequest? {
    let controllerId = pigeonVar_list[0] as! Int64

    return ControllerRequest(
      controllerId: controllerId
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId
    ]
  }
  static func == (lhs: ControllerRequest, rhs: ControllerRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SeekRequest: Hashable {
  var controllerId: Int64
  var positionMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SeekRequest? {
    let controllerId = pigeonVar_list[0] as! Int64
    let positionMs = pigeonVar_list[1] as! Int64

    return SeekRequest(
      controllerId: controllerId,
      positionMs: positionMs
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      positionMs,
    ]
  }
  static func == (lhs: SeekRequest, rhs: SeekRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VisibleIndexRequest: Hashable {
  var index: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisibleIndexRequest? {
    let index = pigeonVar_list[0] as! Int64

    return VisibleIndexRequest(
      index: index
    )
  }
  func toList() -> [Any?] {
    return [
      index
    ]
  }
  static func == (lhs: VisibleIndexRequest, rhs: VisibleIndexRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttachViewRequest: Hashable {
  var controllerId: Int64
  var viewId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttachViewRequest? {
    let controllerId = pigeonVar_list[0] as! Int64
    let viewId = pigeonVar_list[1] as! Int64

    return AttachViewRequest(
      controllerId: controllerId,
      viewId: viewId
    )
  }
  func toList() -> [Any?] {
    return [
      controllerId,
      viewId,
    ]
  }
  static func == (lhs: AttachViewRequest, rhs: AttachViewRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitializeRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return VideoSourceMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return PreloadRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return CreateControllerRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return ControllerRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return SeekRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return VisibleIndexRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return AttachViewRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitializeRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VideoSourceMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PreloadRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CreateControllerRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ControllerRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? SeekRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VisibleIndexRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AttachViewRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeReelsPlayerHostApi {
  func initialize(request: InitializeRequest) throws
  func preload(request: PreloadRequest) throws
  func createController(request: CreateControllerRequest) throws -> Int64
  func disposeController(request: ControllerRequest) throws
  func play(request: ControllerRequest) throws
  func pause(request: ControllerRequest) throws
  func seekTo(request: SeekRequest) throws
  func setVisibleIndex(request: VisibleIndexRequest) throws
  func clearCache() throws
  func attachView(request: AttachViewRequest) throws
  func detachView(request: ControllerRequest) throws
  func disposeAll() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeReelsPlayerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `NativeReelsPlayerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeReelsPlayerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! InitializeRequest
        do {
          try api.initialize(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let preloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.preload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      preloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PreloadRequest
        do {
          try api.preload(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      preloadChannel.setMessageHandler(nil)
    }
    let createControllerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.createController\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createControllerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CreateControllerRequest
        do {
          let result = try api.createController(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createControllerChannel.setMessageHandler(nil)
    }
    let disposeControllerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.disposeController\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeControllerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.disposeController(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeControllerChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.play(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.pause(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SeekRequest
        do {
          try api.seekTo(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    let setVisibleIndexChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.setVisibleIndex\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVisibleIndexChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VisibleIndexRequest
        do {
          try api.setVisibleIndex(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVisibleIndexChannel.setMessageHandler(nil)
    }
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.clearCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { _, reply in
        do {
          try api.clearCache()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
    let attachViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.attachView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      attachViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AttachViewRequest
        do {
          try api.attachView(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      attachViewChannel.setMessageHandler(nil)
    }
    let detachViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.detachView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detachViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ControllerRequest
        do {
          try api.detachView(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      detachViewChannel.setMessageHandler(nil)
    }
    let disposeAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_reels_player.NativeReelsPlayerHostApi.disposeAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeAllChannel.setMessageHandler { _, reply in
        do {
          try api.disposeAll()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeAllChannel.setMessageHandler(nil)
    }
  }
}
