// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.native_feed_player

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class InitializeRequest (
  val maxCachedPlayers: Long,
  val preloadCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializeRequest {
      val maxCachedPlayers = pigeonVar_list[0] as Long
      val preloadCount = pigeonVar_list[1] as Long
      return InitializeRequest(maxCachedPlayers, preloadCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxCachedPlayers,
      preloadCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InitializeRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoSourceMessage (
  val url: String,
  val index: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoSourceMessage {
      val url = pigeonVar_list[0] as String
      val index = pigeonVar_list[1] as Long
      return VideoSourceMessage(url, index)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      index,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VideoSourceMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreloadRequest (
  val sources: List<VideoSourceMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreloadRequest {
      val sources = pigeonVar_list[0] as List<VideoSourceMessage>
      return PreloadRequest(sources)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sources,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PreloadRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateControllerRequest (
  val url: String,
  val index: Long,
  val autoPlay: Boolean,
  val looping: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateControllerRequest {
      val url = pigeonVar_list[0] as String
      val index = pigeonVar_list[1] as Long
      val autoPlay = pigeonVar_list[2] as Boolean
      val looping = pigeonVar_list[3] as Boolean
      return CreateControllerRequest(url, index, autoPlay, looping)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      index,
      autoPlay,
      looping,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateControllerRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ControllerRequest (
  val controllerId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ControllerRequest {
      val controllerId = pigeonVar_list[0] as Long
      return ControllerRequest(controllerId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ControllerRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SeekRequest (
  val controllerId: Long,
  val positionMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SeekRequest {
      val controllerId = pigeonVar_list[0] as Long
      val positionMs = pigeonVar_list[1] as Long
      return SeekRequest(controllerId, positionMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      positionMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SeekRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VisibleIndexRequest (
  val index: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VisibleIndexRequest {
      val index = pigeonVar_list[0] as Long
      return VisibleIndexRequest(index)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VisibleIndexRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttachViewRequest (
  val controllerId: Long,
  val viewId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttachViewRequest {
      val controllerId = pigeonVar_list[0] as Long
      val viewId = pigeonVar_list[1] as Long
      return AttachViewRequest(controllerId, viewId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      viewId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AttachViewRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializeRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoSourceMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreloadRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateControllerRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ControllerRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SeekRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VisibleIndexRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttachViewRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitializeRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is VideoSourceMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PreloadRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CreateControllerRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ControllerRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SeekRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VisibleIndexRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is AttachViewRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeFeedPlayerHostApi {
  fun initialize(request: InitializeRequest)
  fun preload(request: PreloadRequest)
  fun createController(request: CreateControllerRequest): Long
  fun disposeController(request: ControllerRequest)
  fun play(request: ControllerRequest)
  fun pause(request: ControllerRequest)
  fun seekTo(request: SeekRequest)
  fun setVisibleIndex(request: VisibleIndexRequest)
  fun clearCache()
  fun attachView(request: AttachViewRequest)
  fun detachView(request: ControllerRequest)
  fun disposeAll()

  companion object {
    /** The codec used by NativeFeedPlayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NativeFeedPlayerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeFeedPlayerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InitializeRequest
            val wrapped: List<Any?> = try {
              api.initialize(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.preload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PreloadRequest
            val wrapped: List<Any?> = try {
              api.preload(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.createController$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CreateControllerRequest
            val wrapped: List<Any?> = try {
              listOf(api.createController(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.disposeController$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.disposeController(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.play(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.pause(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SeekRequest
            val wrapped: List<Any?> = try {
              api.seekTo(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setVisibleIndex$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VisibleIndexRequest
            val wrapped: List<Any?> = try {
              api.setVisibleIndex(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.clearCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearCache()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.attachView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AttachViewRequest
            val wrapped: List<Any?> = try {
              api.attachView(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.detachView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.detachView(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.disposeAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disposeAll()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
