// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.aswinsubhash.native_feed_player

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** How a source should be treated by the native loader. */
enum class FeedMediaKindMessage(val raw: Int) {
  AUTO(0),
  PROGRESSIVE(1),
  HLS(2);

  companion object {
    fun ofRaw(raw: Int): FeedMediaKindMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Native playback status for a single controller. */
enum class PlaybackStatusMessage(val raw: Int) {
  IDLE(0),
  PREPARING(1),
  READY(2),
  PLAYING(3),
  PAUSED(4),
  BUFFERING(5),
  COMPLETED(6),
  ERROR(7),
  RELEASED(8);

  companion object {
    fun ofRaw(raw: Int): PlaybackStatusMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Why a controller stopped existing. */
enum class ReleaseReasonMessage(val raw: Int) {
  DISPOSED(0),
  EVICTED(1),
  ERROR(2),
  ENGINE_DETACHED(3);

  companion object {
    fun ofRaw(raw: Int): ReleaseReasonMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** How native video output reaches the Flutter scene. */
enum class RenderModeMessage(val raw: Int) {
  /** A native view composited by Flutter's platform-view layer. */
  PLATFORM_VIEW(0),
  /** Frames copied into a Flutter texture, drawn by the Flutter renderer. */
  TEXTURE(1);

  companion object {
    fun ofRaw(raw: Int): RenderModeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FeedSourceMessage (
  /** Caller-owned stable identifier. Survives pagination and reordering. */
  val id: String,
  val uri: String,
  /** Position in the feed, used only to rank preload priority. */
  val rank: Long,
  val kind: FeedMediaKindMessage,
  val headers: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FeedSourceMessage {
      val id = pigeonVar_list[0] as String
      val uri = pigeonVar_list[1] as String
      val rank = pigeonVar_list[2] as Long
      val kind = pigeonVar_list[3] as FeedMediaKindMessage
      val headers = pigeonVar_list[4] as Map<String, String>
      return FeedSourceMessage(id, uri, rank, kind, headers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      uri,
      rank,
      kind,
      headers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FeedSourceMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CachePolicyMessage (
  val enabled: Boolean,
  val maxBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CachePolicyMessage {
      val enabled = pigeonVar_list[0] as Boolean
      val maxBytes = pigeonVar_list[1] as Long
      return CachePolicyMessage(enabled, maxBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      maxBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CachePolicyMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AudioPolicyMessage (
  val muted: Boolean,
  val volume: Double,
  val handleAudioFocus: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioPolicyMessage {
      val muted = pigeonVar_list[0] as Boolean
      val volume = pigeonVar_list[1] as Double
      val handleAudioFocus = pigeonVar_list[2] as Boolean
      return AudioPolicyMessage(muted, volume, handleAudioFocus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      muted,
      volume,
      handleAudioFocus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AudioPolicyMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FeedPlayerConfigMessage (
  val maxActivePlayers: Long,
  val preloadAhead: Long,
  val preloadBehind: Long,
  val maxConcurrentPreloads: Long,
  val positionUpdateIntervalMs: Long,
  val renderMode: RenderModeMessage,
  val cache: CachePolicyMessage,
  val audio: AudioPolicyMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FeedPlayerConfigMessage {
      val maxActivePlayers = pigeonVar_list[0] as Long
      val preloadAhead = pigeonVar_list[1] as Long
      val preloadBehind = pigeonVar_list[2] as Long
      val maxConcurrentPreloads = pigeonVar_list[3] as Long
      val positionUpdateIntervalMs = pigeonVar_list[4] as Long
      val renderMode = pigeonVar_list[5] as RenderModeMessage
      val cache = pigeonVar_list[6] as CachePolicyMessage
      val audio = pigeonVar_list[7] as AudioPolicyMessage
      return FeedPlayerConfigMessage(maxActivePlayers, preloadAhead, preloadBehind, maxConcurrentPreloads, positionUpdateIntervalMs, renderMode, cache, audio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxActivePlayers,
      preloadAhead,
      preloadBehind,
      maxConcurrentPreloads,
      positionUpdateIntervalMs,
      renderMode,
      cache,
      audio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FeedPlayerConfigMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateControllerRequest (
  val sourceId: String,
  val autoPlay: Boolean,
  val looping: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateControllerRequest {
      val sourceId = pigeonVar_list[0] as String
      val autoPlay = pigeonVar_list[1] as Boolean
      val looping = pigeonVar_list[2] as Boolean
      return CreateControllerRequest(sourceId, autoPlay, looping)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceId,
      autoPlay,
      looping,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateControllerRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ControllerRequest (
  val controllerId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ControllerRequest {
      val controllerId = pigeonVar_list[0] as Long
      return ControllerRequest(controllerId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ControllerRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SeekRequest (
  val controllerId: Long,
  val positionMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SeekRequest {
      val controllerId = pigeonVar_list[0] as Long
      val positionMs = pigeonVar_list[1] as Long
      return SeekRequest(controllerId, positionMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      positionMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SeekRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VisibleSourceRequest (
  val sourceId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VisibleSourceRequest {
      val sourceId = pigeonVar_list[0] as String
      return VisibleSourceRequest(sourceId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VisibleSourceRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ControllerDoubleRequest (
  val controllerId: Long,
  val value: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ControllerDoubleRequest {
      val controllerId = pigeonVar_list[0] as Long
      val value = pigeonVar_list[1] as Double
      return ControllerDoubleRequest(controllerId, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ControllerDoubleRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ControllerFlagRequest (
  val controllerId: Long,
  val value: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ControllerFlagRequest {
      val controllerId = pigeonVar_list[0] as Long
      val value = pigeonVar_list[1] as Boolean
      return ControllerFlagRequest(controllerId, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ControllerFlagRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttachViewRequest (
  val controllerId: Long,
  val viewId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttachViewRequest {
      val controllerId = pigeonVar_list[0] as Long
      val viewId = pigeonVar_list[1] as Long
      return AttachViewRequest(controllerId, viewId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      viewId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AttachViewRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SourceIdsRequest (
  val sourceIds: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SourceIdsRequest {
      val sourceIds = pigeonVar_list[0] as List<String>
      return SourceIdsRequest(sourceIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceIds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SourceIdsRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CacheStatusMessage (
  val sourceId: String,
  val cachedBytes: Long,
  val totalBytes: Long,
  val isComplete: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CacheStatusMessage {
      val sourceId = pigeonVar_list[0] as String
      val cachedBytes = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      val isComplete = pigeonVar_list[3] as Boolean
      return CacheStatusMessage(sourceId, cachedBytes, totalBytes, isComplete)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceId,
      cachedBytes,
      totalBytes,
      isComplete,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CacheStatusMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackErrorMessage (
  val code: String,
  val message: String,
  val isRecoverable: Boolean,
  val platformCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackErrorMessage {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val isRecoverable = pigeonVar_list[2] as Boolean
      val platformCode = pigeonVar_list[3] as String?
      return PlaybackErrorMessage(code, message, isRecoverable, platformCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      isRecoverable,
      platformCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlaybackErrorMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackStateEvent (
  val controllerId: Long,
  val status: PlaybackStatusMessage,
  val error: PlaybackErrorMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackStateEvent {
      val controllerId = pigeonVar_list[0] as Long
      val status = pigeonVar_list[1] as PlaybackStatusMessage
      val error = pigeonVar_list[2] as PlaybackErrorMessage?
      return PlaybackStateEvent(controllerId, status, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      status,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlaybackStateEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PositionEvent (
  val controllerId: Long,
  val positionMs: Long,
  val bufferedPositionMs: Long? = null,
  val durationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PositionEvent {
      val controllerId = pigeonVar_list[0] as Long
      val positionMs = pigeonVar_list[1] as Long
      val bufferedPositionMs = pigeonVar_list[2] as Long?
      val durationMs = pigeonVar_list[3] as Long?
      return PositionEvent(controllerId, positionMs, bufferedPositionMs, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      positionMs,
      bufferedPositionMs,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PositionEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MetricsEvent (
  val controllerId: Long,
  val rebufferCount: Long,
  /** Monotonic total for the controller's lifetime on both platforms. */
  val droppedFrames: Long,
  val timestampMs: Long,
  /** Milliseconds from controller creation to the first rendered video frame. */
  val firstFrameLatencyMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MetricsEvent {
      val controllerId = pigeonVar_list[0] as Long
      val rebufferCount = pigeonVar_list[1] as Long
      val droppedFrames = pigeonVar_list[2] as Long
      val timestampMs = pigeonVar_list[3] as Long
      val firstFrameLatencyMs = pigeonVar_list[4] as Long?
      return MetricsEvent(controllerId, rebufferCount, droppedFrames, timestampMs, firstFrameLatencyMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      rebufferCount,
      droppedFrames,
      timestampMs,
      firstFrameLatencyMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MetricsEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoSizeEvent (
  val controllerId: Long,
  /** Decoded pixel dimensions, before [rotationDegrees] is applied. */
  val width: Long,
  val height: Long,
  /** Clockwise rotation the renderer must apply, in degrees. */
  val rotationDegrees: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoSizeEvent {
      val controllerId = pigeonVar_list[0] as Long
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val rotationDegrees = pigeonVar_list[3] as Long
      return VideoSizeEvent(controllerId, width, height, rotationDegrees)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      width,
      height,
      rotationDegrees,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VideoSizeEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ControllerLifecycleEvent (
  val controllerId: Long,
  val reason: ReleaseReasonMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ControllerLifecycleEvent {
      val controllerId = pigeonVar_list[0] as Long
      val reason = pigeonVar_list[1] as ReleaseReasonMessage
      return ControllerLifecycleEvent(controllerId, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      controllerId,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ControllerLifecycleEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FeedMediaKindMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlaybackStatusMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ReleaseReasonMessage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RenderModeMessage.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FeedSourceMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CachePolicyMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioPolicyMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FeedPlayerConfigMessage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateControllerRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ControllerRequest.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SeekRequest.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VisibleSourceRequest.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ControllerDoubleRequest.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ControllerFlagRequest.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttachViewRequest.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SourceIdsRequest.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CacheStatusMessage.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackErrorMessage.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackStateEvent.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PositionEvent.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MetricsEvent.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoSizeEvent.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ControllerLifecycleEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FeedMediaKindMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlaybackStatusMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ReleaseReasonMessage -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is RenderModeMessage -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is FeedSourceMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CachePolicyMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is AudioPolicyMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is FeedPlayerConfigMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CreateControllerRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ControllerRequest -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is SeekRequest -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is VisibleSourceRequest -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ControllerDoubleRequest -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is ControllerFlagRequest -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is AttachViewRequest -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is SourceIdsRequest -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is CacheStatusMessage -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is PlaybackErrorMessage -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is PlaybackStateEvent -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is PositionEvent -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is MetricsEvent -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is VideoSizeEvent -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is ControllerLifecycleEvent -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeFeedPlayerHostApi {
  fun initialize(config: FeedPlayerConfigMessage)
  /** Replaces the whole feed. */
  fun setSources(sources: List<FeedSourceMessage>)
  /** Appends a page without renumbering existing sources. */
  fun appendSources(sources: List<FeedSourceMessage>)
  fun removeSources(request: SourceIdsRequest)
  fun createController(request: CreateControllerRequest): Long
  fun disposeController(request: ControllerRequest)
  fun play(request: ControllerRequest)
  fun pause(request: ControllerRequest)
  fun seekTo(request: SeekRequest)
  fun setVolume(request: ControllerDoubleRequest)
  fun setMuted(request: ControllerFlagRequest)
  fun setPlaybackSpeed(request: ControllerDoubleRequest)
  fun setLooping(request: ControllerFlagRequest)
  /** Applies to every controller, current and future. */
  fun setAudioPolicy(policy: AudioPolicyMessage)
  fun setVisibleSource(request: VisibleSourceRequest)
  /**
   * Drops persisted media bytes for the given sources, or all of them when
   * the list is empty.
   */
  fun evictCachedMedia(request: SourceIdsRequest)
  fun clearMediaCache()
  fun cacheStatus(request: VisibleSourceRequest): CacheStatusMessage
  fun cacheUsageBytes(): Long
  fun attachView(request: AttachViewRequest)
  fun detachView(request: ControllerRequest)
  /** Binds the controller to a Flutter texture and returns its id. */
  fun attachTexture(request: ControllerRequest): Long
  fun detachTexture(request: ControllerRequest)
  fun disposeAll()

  companion object {
    /** The codec used by NativeFeedPlayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NativeFeedPlayerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeFeedPlayerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as FeedPlayerConfigMessage
            val wrapped: List<Any?> = try {
              api.initialize(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourcesArg = args[0] as List<FeedSourceMessage>
            val wrapped: List<Any?> = try {
              api.setSources(sourcesArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.appendSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourcesArg = args[0] as List<FeedSourceMessage>
            val wrapped: List<Any?> = try {
              api.appendSources(sourcesArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.removeSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SourceIdsRequest
            val wrapped: List<Any?> = try {
              api.removeSources(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.createController$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CreateControllerRequest
            val wrapped: List<Any?> = try {
              listOf(api.createController(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.disposeController$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.disposeController(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.play(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.pause(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SeekRequest
            val wrapped: List<Any?> = try {
              api.seekTo(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerDoubleRequest
            val wrapped: List<Any?> = try {
              api.setVolume(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerFlagRequest
            val wrapped: List<Any?> = try {
              api.setMuted(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setPlaybackSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerDoubleRequest
            val wrapped: List<Any?> = try {
              api.setPlaybackSpeed(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setLooping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerFlagRequest
            val wrapped: List<Any?> = try {
              api.setLooping(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setAudioPolicy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val policyArg = args[0] as AudioPolicyMessage
            val wrapped: List<Any?> = try {
              api.setAudioPolicy(policyArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.setVisibleSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VisibleSourceRequest
            val wrapped: List<Any?> = try {
              api.setVisibleSource(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.evictCachedMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SourceIdsRequest
            val wrapped: List<Any?> = try {
              api.evictCachedMedia(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.clearMediaCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearMediaCache()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.cacheStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VisibleSourceRequest
            val wrapped: List<Any?> = try {
              listOf(api.cacheStatus(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.cacheUsageBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.cacheUsageBytes())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.attachView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AttachViewRequest
            val wrapped: List<Any?> = try {
              api.attachView(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.detachView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.detachView(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.attachTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              listOf(api.attachTexture(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.detachTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ControllerRequest
            val wrapped: List<Any?> = try {
              api.detachTexture(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerHostApi.disposeAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disposeAll()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class PlaybackStateEventsStreamHandler : MessagesPigeonEventChannelWrapper<PlaybackStateEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: PlaybackStateEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.playbackStateEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlaybackStateEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlaybackStateEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class PositionEventsStreamHandler : MessagesPigeonEventChannelWrapper<PositionEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: PositionEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.positionEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PositionEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PositionEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class MetricsEventsStreamHandler : MessagesPigeonEventChannelWrapper<MetricsEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: MetricsEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.metricsEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<MetricsEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<MetricsEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class VideoSizeEventsStreamHandler : MessagesPigeonEventChannelWrapper<VideoSizeEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: VideoSizeEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.videoSizeEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<VideoSizeEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<VideoSizeEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class LifecycleEventsStreamHandler : MessagesPigeonEventChannelWrapper<ControllerLifecycleEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: LifecycleEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.native_feed_player.NativeFeedPlayerEventApi.lifecycleEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<ControllerLifecycleEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ControllerLifecycleEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
